### ISSUE TITLE
Add a "Works with AVA" section.

### ISSUE THREAD

**Issue by jamestalmage** [avajs/awesome-ava#11]
Highlight some modules that embrace Promise/Observable based API's, and make testing with AVA better.

Some thoughts:
- `delay`
- `execa`
- `pify`

**Comment by sindresorhus** [comment]
👍 Should include use-examples or description of how they're useful with AVA. I'd imagine `execa` and `pify` could be individual recipes for AVA at some point.

**Comment by SamVerschueren** [comment]
`rfpify` - [example](https://github.com/kevva/screenshot-stream/blob/master/test/test.js#L65)

**Comment by kevva** [comment]
- `get-stream`

**Comment by vadimdemedes** [comment]
"Works with AVA" section is in readme now.
