### ISSUE TITLE
Add Vim snippets

### ISSUE THREAD

**Issue by zhangyuheng** [avajs/awesome-ava#9]
Please consider adding ultisnips of ava for vim editor.

Thanks!

ref:
- engine plugin: https://github.com/SirVer/ultisnips
- common snippets plugin: https://github.com/honza/vim-snippets/tree/master/UltiSnips

**Comment by sindresorhus** [comment]
I don't have any experience with Vim, but I did a tweet about it: https://twitter.com/ava__js/status/729190859313270785 ;)

## 

For anyone wanting to do this, you should be able to port the existing Atom snippets pretty easily:
- https://github.com/sindresorhus/atom-ava/blob/master/snippets/assertions.json
- https://github.com/sindresorhus/atom-ava/blob/master/snippets/ava.json

**Comment by ahmedelgabri** [comment]
@zhangyuheng I needed this anyway, so I created one here https://github.com/ahmedelgabri/vim-ava-snippets

One thing to note though that having a `.` in a trigger ex: `t.is`, etc... _might_ be an issue but for now it's working maybe I'll change this to `-` instead.

**Comment by sindresorhus** [comment]
Wow. That was fast. Thank you @ahmedelgabri! Added :)

**Comment by sindresorhus** [comment]
@zhangyuheng Open issues on https://github.com/ahmedelgabri/vim-ava-snippets for any improvements or bugs.
